name: tmdb_app
description: The Movie Database App.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  auto_route: ^0.6.9
  cloud_firestore: ^0.14.3
  dartz: ^0.9.2
  deep_pick: ^0.5.1
  firebase_auth: ^0.18.3
  firebase_core: ^0.5.2
  flushbar: ^1.10.4
  flutter_bloc: ^6.1.0
  flutter_dotenv: ^2.1.0
  freezed_annotation: ^0.12.0
  get_it: ^5.0.1
  google_sign_in: ^4.5.6
  http: ^0.12.2
  injectable: ^1.0.5
  json_annotation: ^3.1.0
  uuid: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^0.6.10
  bloc_test: ^7.1.0
  build_runner: null
  freezed: ^0.12.2
  injectable_generator: ^1.0.6
  json_serializable: ^3.5.0
  lint: ^1.3.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/
